### ISSUE TITLE
 connect_mqtt：Connection failed, the log shows that the maximum number of links has been exceeded

### ISSUE THREAD

**Issue by 83943958** [MinhHuyDev/fbchat-v2#12]
resort：
After logging in, I listened to messages and the result was that my account was banned after running, with a prompt prohibiting automation 

connect_mqtt：

 **Connection failed, the log shows that the maximum number of links has been exceeded （50）**

-main.py--

 cookie = 'my cookie'
     i = __facebookToolsV2.dataGetHome(cookie)
     fbt = __facebookToolsV2.fbTools(i, 0)
     _ = listeningEvent(fbt, i)
     _.get_last_seq_id()
     _.connect_mqtt()

thanks!!!

**Comment by MinhHuyDev** [comment]
I still don't fully understand the problem you are having. If possible, please contact me: [Telegram](https://t.me/mhuydev)
