### ISSUE TITLE
Seens not support the business.facebook.com

### ISSUE THREAD

**Issue by af913337456** [MinhHuyDev/fbchat-v2#17]
Hi, i use this project in `business.facebook.com`, same cookies as the `www.facebook.com` and the request json, but can't receive the message from the PUBLICe_PAGE. @MinhHuyDev

**Comment by MinhHuyDev** [comment]
Bro, If you use cookies from *Fanpage Profile*, messages will not be received or sent. You can only use this package for your personal Facebook account!
