### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by taoshiyu** [MinhHuyDev/fbchat-v2#18]
websockets connect  TimeError
 always  at pycharm/cmd
 never at chrome/facebook/homepage/console
alway at chome/other WebSite/console
why?????????
checked for 1000 times,F**K
by the way i use VPN
help me!!!!

**Comment by MinhHuyDev** [comment]
Please turn off VPN and try again. If there are still errors, please contact me via: [`Telegram`](https://t.me/mhuydev)
