### ISSUE TITLE
Where is setCookies = "<cookies get from Facebook>"

### ISSUE THREAD

**Issue by nongvantinh** [MinhHuyDev/fbchat-v2#7]
In the provided example, there is a variable `setCookies` initialized with the value "<cookies get from Facebook>". I'm wondering where I can obtain these cookies. Is there any code implementation available for this purpose?

**Comment by MinhHuyDev** [comment]
Bạn có thể lấy qua việc truy cập vào [Facebook](https://www.facebook.com) đã đăng nhập sẵn sau đó nhấn **F12** để mở phần *DevTools* của trình duyệt. Chọn 1 requests bất kì của Facebook (**KHÔNG NÊN CHỌN REQUESTS LÀ ẢNH**) ở phần Headers của Requests bạn sẽ thấy Cookies (Nếu không thấy hãy chọn 1 requests khác)

**Comment by nongvantinh** [comment]
Thanks. You did great work. Do you intend to implement the `send_typing` to the target?

**Comment by MinhHuyDev** [comment]
ý của bạn là có thể chọn gửi đến **threading**, **user** và **fanpage** ?

**Comment by nongvantinh** [comment]
No, usually, when a user composes a message before sending, there is an ellipsis (...) that appears in the message thread to indicate that they are writing the message. It would be nice if this library contained that functionality.

**Comment by MinhHuyDev** [comment]
À, tôi hiểu. Tính năng này sẽ làm đi việc gửi tin nhắn chậm hơn so với bình thường (**delay**)
