### ISSUE TITLE
[Feature Request] managing/adding marketplace listngs

### ISSUE THREAD

**Issue by syrex1013** [MinhHuyDev/fbchat-v2#8]
Hello,
Would likr to talk with you on telegram, but I see it has been deleted. Is there any new contact info to you?

**Comment by syrex1013** [comment]
I addef you on FB, if it is you lol xD

**Comment by MinhHuyDev** [comment]
New Telegram: [click here](https://t.me/mhuydev)

**Comment by syrex1013** [comment]
Great, writing to you!
